
############## Obtener la lista de enfermedades
# GET http://localhost:8081/api/v1/enfermedades
# Content-Type: application/json


############## Enviar notificaciones al front-end
# # POST http://localhost:8081/api/v1/notificacion/evento?message="hay nuevos mensajes para ti!!"
# POST http://localhost:8081/api/v1/notificacion/evento
# Content-Type: application/json


POST http://localhost:8081/api/v1/consulta/paciente
Content-Type: application/json

{
    "idEnfermedad": 1,
    "idIps": 0,
    "page": 2,
    "limit": 2,
    "desde": "",
    "hasta": "",
    "tipoDocumento": "fff",
    "documento": "32258927"
}