
############## Obtener la lista de enfermedades
# GET http://localhost:8081/api/v1/enfermedades
# Content-Type: application/json


############## Enviar notificaciones al front-end
# POST http://localhost:8081/api/v1/notificacion/evento?message="hay nuevos mensajes para ti!!"
POST http://localhost:8081/api/v1/notificacion/evento?message="hay nuevos mensajes para ti!!"
Content-Type: application/json
